In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])

In [3]:
print("array1 array 형태:", type(array1))

array1 array 형태: <class 'numpy.ndarray'>


In [5]:
print("array1 array 형태:", array1.shape)

array1 array 형태: (3,)


In [7]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print(array2)

[[1 2 3]
 [2 3 4]]


In [8]:
print("array2 type:", type(array2))

array2 type: <class 'numpy.ndarray'>


In [9]:
print("array2 shape:", array2.shape)

array2 shape: (2, 3)


In [11]:
array3 = np.array([[1, 2, 3]])
print("array 3 type:", type(array3))
print("array 3 shape:", array3.shape)

array 3 type: <class 'numpy.ndarray'>
array 3 shape: (1, 3)


In [14]:
print("array1: {:0}차원, array2: {:1}차원, array3: {:2}차원".format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [15]:
list1 = [1, 2, 3]

In [17]:
print(type(list1))

<class 'list'>


In [18]:
array1 = np.array(list1)
print(type(array1))

<class 'numpy.ndarray'>


In [19]:
print(array1, array1.dtype)

[1 2 3] int32


같은 데이터 타입만 가능한 array에 다른 data type 같이 입력하였을 때

In [20]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [21]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[ 1.  2.  3.] float64


결과: 더 큰 데이터 타입으로 형변환 일괄적용 첫번째 경우 문자열로, 두번째 경우 실수형으로 

astype()메소드로 타입변경하기 -> 주로 메모리 절약해야할때 ex) float를 int로

In [22]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float')

In [24]:
print(array_float, array_float.dtype)

[ 1.  2.  3.] float64


In [26]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [27]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


nd.array 편리하게 생성 - 편리하게 초기화 생성

In [28]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [29]:
sequence_array2 = np.arange(2, 10, 2)
print(sequence_array2)
print(sequence_array2.dtype,sequence_array2.shape)

[2 4 6 8]
int32 (4,)


In [30]:
zero_array = np.zeros((3, 2), dtype = 'int32') ##default는 float64
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [32]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
float64 (3, 2)


reshape() method

In [3]:
array1 = np.arange(10)
print("array1:\n", array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [4]:
array2 = array1.reshape(2, 5)
print("array2:\n", array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
array3 = array1.reshape(5,2)
print("array3:\n", array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape -1 인자 -> (-1, 1)로 많이 사용:: 한개의 칼럼

In [6]:
array1 = np.arange(10) 
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
array2 = array1.reshape(-1, 5)
print("array2 shape:", array2.shape)

array2 shape: (2, 5)


In [8]:
array3 = array1.reshape(5, -1)
print("array3 shape:", array3.shape)

array3 shape: (5, 2)


reshape로 형태 통일해 stack이나 concat으로 결합 많이 사용
tolist()로 list형태 변환 가능 -> 출력시 시각적 이해 더 쉬움

In [9]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print("array3d:\n", array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [10]:
array5 = array3d.reshape(-1,1)
print("array5:\n", array5.tolist())

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]


In [11]:
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


인덱싱 - 특정 데이터 선택 :: 해당인덱스값지정/슬라이싱/fancy indexing(리스트/ndarray형태로지정)/boolean indexint(조건/true선택)

In [12]:
array1 = np.arange(start = 1, stop = 10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [13]:
print("맨 뒤의 값:", array1[-1], "맨 뒤에서 두번째 값:", array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [14]:
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [15]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


사실은 row, col 아닌 axis = 0 : row, axis = 1 : col wmr [axis 0 = 0, axis 1 = 1] 이 정화ㄱ표현 생략시 axis0

In [17]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array4 = array1[:3]
print(array4)

[1 2 3]


In [20]:
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
array3 = array2d[[0,1],2]
print(array3)

[3 6]


In [23]:
array4 = array2d[[0, 1],0:2]
print(array4)

[[1 2]
 [4 5]]


In [24]:
array5 = array2d[[0,1]]
print(array5)

[[1 2 3]
 [4 5 6]]


In [25]:
array1 = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print('array1d>5불린인덱싱결과값:', array3)

array1d>5불린인덱싱결과값: [6 7 8 9]


In [26]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [27]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


정렬-sort, argsort

In [32]:
org_array = np.array([3, 1, 9, 5])
print(org_array)
#오름차순
sort_array1 = np.sort(org_array)
sort_array2 = org_array.sort() ## 원본을 정렬해버림
print(sort_array1)
print(sort_array2)
print(org_array)
#내림차순
org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[3 1 9 5]
[1 3 5 9]
None
[1 3 5 9]
[3 1 9 5]
[9 5 3 1]


In [33]:
#2차원
array2d = np.array([[8, 12],
                   [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우방향정렬',sort_array2d_axis0)

로우방향정렬 [[ 7  1]
 [ 8 12]]


In [34]:
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼방향정렬',sort_array2d_axis1)

칼럼방향정렬 [[ 8 12]
 [ 1  7]]


In [35]:
#원본행렬 정렬 시 기존 원본 행렬 원소 대한 인덱스 필요시 argsort이용
#np.argsort() : 원본행렬 인덱스를 nparray로 반환
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


# 선형대수 연산

In [36]:
#행렬내적 = 행렬곱
#np.dot(A, B)
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [38]:
#전치행렬
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [2]:
a = [[1, 2], [2, 1]]
b = [[4, 1], [2, 2]]
np.cross(a, b)

array([-7,  2])